# Speed up the build
git:
  depth: false
branches:
  only:
  - "master"
cache: pip

# How to build
language: python
python:
  - "3.7"
  - "3.8"
os: linux
install:
  - pip install tox==3.14.5
script:
  - tox