# Speed up the build
git:
  depth: false
cache: pip

# How to build
language: python
python:
  - '3.7'
  - '3.8'
  - '3.9'
os: linux
dist: focal
install:
  - pip install tox==3.23.0
script:
  - tox

# Deploy to PyPi on each version tag
deploy:
  provider: pypi
  user: __token__
  password:
    secure: hoAJ+R8DpGu2WL0qASTOri8y1MwCCb/UI97OzUzQqdlZzxjjQuiZSMuiWhanq7bve/9Gsv5ZN9EKVskLOdmJr8xlhlCQP9uIk3ExTxCIgv0R0dhjw9QgCXr3FuN7aUxsLpxJ23Ttx12tY6OBAP63L7C2zzm6Y54auxQViqGRnd/PerKMd0vqKbqSzXSFUKO5tL5Vp9FsuwSOXZyyKjif2mzvWqXGl2wHxk911WTlqOAGRzhN1BMGJ1TETgvagtmF9gmqy3WMqaY5uSMs4iw3+G7gs3ofefc2hGJzKCM+TrDo2ssIWbQzaT4Hhmdt0kGb5iAKBm8Wwf9RaG5dSRJm/9VQGWbEQcDdLEuidkR1JNwSX3joc3Bd5nVXM6R85a28k0kr5aLN64vhlIARNAq+ca5toqegXenx6MdOydti9hB2Hq80LmhsumtakSrGATTHo9IZ1wlNHPUYKUE2ERYPpyKAf8gByFNHlx4Z+3Lqy3o3G+zZqUZ3aeMwRikKln8lZfp0tkKdXMsEieRIBF6C6zOOIPIMHHcU6lDhyez7jhxNBaNkNWymofTVoUO7754LvSXwxMAu/dZ1YcXFiTyg4w+OZ4NNN0K7zU3eEHeYhMRxczLNf1kMgZ4M81RSI76qrlykxb89zGXrKTltAXhRtrNtC8nPtyrQPxIwuq/EbMQ=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
